/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Using OLD project for Edge Functions, NEW project for database (via SUPABASE_SERVICE_ROLE_KEY env var in functions)
export const projectId = "lqtbeqllyikofkznnhlx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxdGJlcWxseWlrb2Zrem5uaGx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU2MTI4MzEsImV4cCI6MjA4MTE4ODgzMX0.OBPwdU2ZWGP9wECtzPQAUNysIjNPl_Ou_LAn_zb7YT0"
